version: '3'

services:
  esrp-gui: #This is the name of our Nextjs application.
    image: esrsp-gui:latest      
    restart: always
    network_mode: "host"
    environment:
      DB: ${DB}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      SECRET_KEY: ${SECRET_KEY}

